### ISSUE TITLE
Custom whitelist.

### ISSUE THREAD

**Issue by Explorare** [qiuzi/dns2socks#2]
Is this possible to add a function that allows me to use a whitelist to tell DNS2SOCKS these sites in the list would use my ISP's or other DNS server without a SOCKS  proxy? Some video sites I always visit use a CDN that **ONLY** provide service in my area. And I couldn't load video when I use DNS2SOCKS.

**Comment by qiuzi** [comment]
请使用中文

**Comment by Explorare** [comment]
噫，第一次在 gayhub 遇到要求说中文的 ( ´_ゝ`)
我就希望 DNS2SOCKS 增加个类似 PAC 的模式，名单内的站点走 ISP 的 DNS伺服器，比如 B站就会受到很严重的影响，视频读取很慢或者直接无法读取。不过后来想了想，这功能也许没啥用，费点劲修改 hosts 算了。

**Comment by ershiwo** [comment]
@Explorare 我只是围观一下你的英语……

**Comment by Explorare** [comment]
食蕉辣你 ⊂彡☆))∀`)

**Comment by qiuzi** [comment]
dns2socks不带缓存功能就算使用白名单效率依然没有dnsmasq好，如果想更智能灵活可以关注sana项目
https://github.com/XiaoxiaoPu/sans

dns2socks已经没有什么好研究的了

**Comment by Explorare** [comment]
感谢
