### ISSUE TITLE
x

### ISSUE THREAD

**Issue by hillz1** [qiuzi/dns2socks#3]

**Comment by qiuzi** [comment]
$(TARGET_CROSS)gcc -pthread -Wall -Os -o $(PKG_BUILD_DIR)/dns2socks $(PKG_BUILD_DIR)/DNS2SOCKS.c

**Comment by hillz1** [comment]
Can you please write the complete `Makefile` for openwrt? I'm new to linux I have no idea how to create a `Makefile`

**Comment by qiuzi** [comment]
Reference openwrt development documents
ps: It too features a single long-term use is not recommended
