### ISSUE TITLE
如何修改SOCKS server 的端口号？如何修改DNS server地址？

### ISSUE THREAD

**Issue by luckypoem** [qiuzi/dns2socks#9]
hi

yudeMacBook-Air:DNS2SOCKS brite$ sudo ./DNS2SOCKS
Password:

DNS2SOCKS V2.0 (free software, use parameter /? to display help)

SOCKS server 127.0.0.1 port 9050
DNS server   213.73.91.35 port 53
listening on 127.0.0.1 port 53
cache enabled
authentication disabled

如何修改SOCKS server 的端口号？如何修改DNS server地址？

**Comment by qiuzi** [comment]
dns2socks 127.0.0.1:9050 213.73.91.35 53 127.0.0.1:53

**Comment by luckypoem** [comment]
哦，像这样：
sudo ./DNS2SOCKS 127.0.0.1:1080 8.8.8.8:53 127.0.0.1:53
